name: Deploy

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: npm

      - name: Install
        run: npm ci

      - name: Build project
        run: npx nx run ezbud:build

      - name: Upload product-ready build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./dist/apps/ezbud

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with: 
          name: production-files
          path: ./dist/apps/ezbud

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/ezbud